version: 2.1
orbs:
  android: circleci/android@2.0.3
jobs:
  build:
    executor:
      name: android/android-docker
      resource-class: small
      tag: 2024.10.1
    steps:
      - checkout
      

workflows:
  android-workflow:
    jobs:
      - build