version: 2.1
orbs:
  android: circleci/android@2.0.3
jobs:
  build:
    executor:
      name: android/android-docker
      resource-class: xlarge
      tag: 2022.08.1
    steps:
      - checkout

workflows:
  android-workflow:
    jobs:
      - build