name: sandbox1

on:
  workflow_dispatch:

env:
  TZ: Asia/Tokyo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Update Variable
        uses: actions/github-script@v7
        with:
          script: |
            const newValue = parseInt(${{ vars.MY_VARIABLE_1 }}, 10) + 1;
            const result = await github.rest.actions.updateRepoVariable({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'MY_VARIABLE_1',  
                value: newValue.toString(),
            });
            console.log(result);
            console.log(`Variable = ${newValue}`);

      - name: Dump variable value
        run: echo "Variable = ${{ vars.MY_VARIABLE_1 }}"
